### ISSUE TITLE
Age Structured LxMx Schedule tab not allowing editing

### ISSUE THREAD

**Issue by tjkautz** [cbs-rlt/populus#13] opened 2017-12-04 20:33 UTC
Hi, I am teaching 3408W using Populus this semester.  We just discovered 
that in the newest version of Populus, the age-structured modeling does 
not allow us to edit the numbers in the LxMx Schedule tab.  The Leslie 
matrix tab is editable, but I don't want my students to have to learn 
Leslie matrices, which would distract from my learning goals for them.   
Luckily, I have an old version of the Populus program that I will post 
for my students this week. However, this needs to be fixed in the 
current/future versions of this program.  I am attaching the answer key 
to the lab they will be doing (with the questions included) so you can 
try it and see the problem.  Let me know if you have any questions. 

Thanks for keeping Populus alive. 
Best, 
Elizabeth Borer
[populus 2 life table key_revisionsJJG.docx](https://github.com/cbs-rlt/populus/files/1528689/populus.2.life.table.key_revisionsJJG.docx)

**Comment by larsroe** [comment] 2017-12-08 07:22
Are you able to edit any of the cells, or are they all out? The cells should be editable by double-clicking, but some* of them aren't meant to be editable.

* For reference, the code is at ASPGLxMxTableModel::isCellEditable().  It would make sense to make a visual difference if it is editable.

**Comment by larsroe** [comment] 2017-12-08 16:24
The problem is that it's not *setting* the value, even though it is editable.

**Comment by larsroe** [comment] 2017-12-12 20:47
Fix is in https://github.com/cbs-rlt/populus/commit/8b012b60f2972374666752c8e4f23ad9d7656ebe, will be in next release.

**Closed as completed by larsroe** 2017-12-12 20:47 UTC
